#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: c
sudo: false

env:
    global:
    - BYOND_MAJOR="509"
    - BYOND_MINOR="1315"
    matrix:
    - DM_MAPFILE="cyberiad"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="test_away_missions"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip

install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
script:
  - shopt -s globstar
  - (! grep 'step_[xy]' _maps/map_files/**/*.dmm)
  - md5sum -c - <<< "6dc1b6bf583f3bd4176b6df494caa5f1 *html/changelogs/example.yml"
  - python tools/ss13_genchangelog.py html/changelog.html html/changelogs
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} paradise.dme
