#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: generic
sudo: false

git:
  depth: 1

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

env:
  global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1454"
    - BYOND_MACRO_COUNT=4
  matrix:
    - DM_MAPFILE="cyberiad"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="delta"
    - DM_MAPFILE="test_all_maps"

stages:
  - File Checks
  - test

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
script:
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} paradise.dme

jobs:
  include:
    # Basic styling/functionality checks
    - stage: File Checks
      env:
      addons:
      install:
        - pip install --user PyYaml -q
        - pip install --user beautifulsoup4 -q
      before_script: skip
      script:
        - shopt -s globstar
        - (! grep 'step_[xy]' _maps/map_files/**/*.dmm)
        - (num=$(grep -Ern '\\(red|blue|green|black|italic|bold|b|i[^mc])' code/ | wc -l); echo "$num BYOND text macros (expecting ${BYOND_MACRO_COUNT} or fewer)"; [ $num -le ${BYOND_MACRO_COUNT} ])
        - md5sum -c - <<< "6dc1b6bf583f3bd4176b6df494caa5f1 *html/changelogs/example.yml"
        - python tools/ss13_genchangelog.py html/changelog.html html/changelogs

    # Compile NanoUI to make sure it works
    - stage: NanoUI
      language: node_js
      node_js:
        - "9"
      env:
      addons:
      before_install:
        - npm install -g gulp-cli
        - cd ./nano/
      install:
        - npm install --loglevel=error
      before_script:
      script:
        - gulp
