name: Changelog validation

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request_target:
    types: [opened, reopened, edited, labeled, unlabeled, ready_for_review]

jobs:
  CheckCL:
    runs-on: ubuntu-latest
    if: github.repository == 'ss220club/Paradise-SS220' && github.base_ref == 'master' && github.event.pull_request.draft == false
    steps:
      - name: Downloading scripts
        run: |
          wget https://raw.githubusercontent.com/ss220club/Paradise-SS220/master/tools/changelog/check_changelog.py
          wget https://raw.githubusercontent.com/ss220club/Paradise-SS220/master/tools/changelog/tags.yml
      - name: Installing Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.x'
      - name: Installing deps
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Changelog validation
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python check_changelog.py
